### ISSUE TITLE
-

### ISSUE THREAD

**Issue by ghost** [pMattheew/moraes-velleda-test#16]
-

**Comment by patrickkmatias** [comment]
olá Daniel 👋🏾

dúvido muito terem utilizado meu projeto pois nem o terminei =P 

apenas o iniciei com o scaffolding que o Laravel oferece e acabou kk, investi muito mais em implementá-lo em um ambiente de desenvolvimento na nuvem (gitpod) do que desenvolve-lo em si.

eles parecem ser uma empresa seria, tem seus funcionários e etc; creio que para empresas praticarem golpes destes gêneros são mais fáceis de se notar.

ao menos na época tive uma entrevista com o então supervisor deles e uma moça do RH.

desconfie somente se fez realmente uma aplicação com uma utilidade real e que não obteve resposta, caso contrário, se for aplicações simples como CRUD (que foi o que pediram) na internet há zilhões de exemplos funcionais quais eles poderiam fazer utilidade, entende?

boa sorte!

**Comment by ghost** [comment]
-
